services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - confluent
kafka:
  image: confluentinc/cp-kafka:7.4.0
  hostname: kafka
  container_name: kafka
  ports:
    - "9092:9092"
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  depends_on:
    - zookeeper
  networks:
    - confluent

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 010701
      POSTGRES_DB: lazada
    ports:
      - "5433:5432"  # Điều chỉnh cổng này cho phù hợp với cổng bạn đang dùng
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:3.3.1
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    ports:
      - "8080:8080"
    volumes:
      - spark_data:/opt/spark

  app:
    build: .
    container_name: app
    depends_on:
      - kafka
      - postgres
    networks:
      - confluent
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: lazada
      DB_USER: postgres
      DB_PASSWORD: 010701
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: lazada_data_topic

volumes:
  postgres_data:
  spark_data:

networks:
  confluent:
    driver: bridge
